"""
qq.maps._svcb2.search_service_0 & & qq.maps._svcb2.search_service_0()
"""
di = {"info": {"type": 6, "error": 0,
               "request_id": "036110041042e4e264ee9476ea97f874b2490eaf8818",
               "time": 0, "total": 72, "rnum": 10,
               "linetotal": 0, "linenum": 0,
               "stationnum": 0, "hint": 0, "foldtype": 0,
               "foldnum": 0, "foldaddr": "", "marks": 0,
               "qcnum": 0, "qctype": -1,
               "core_query": "", "where_info": "null",
               "what_info": "null", "querytype": 0,
               "need_adjust": 1, "jumpback": 1,
               "jump_to": 0, "cb_version": 2},
      "detail": {"city": {"ccode": 9, "acode": 110106,
                          "cname": "丰台区", "ctype": 3,
                          "level": 12,
                          "pointx": 12944916.120000,
                          "pointy": 4845409.840000,
                          "geotype": 0, "bus": 0,
                          "path": [{"ccode": 9,
                                    "cname": "丰台区"},
                                   {"ccode": 0,
                                    "cname": "北京市"},
                                   {"ccode": 1,
                                    "cname": "中国"}]},
                 "pois": [{"uid": "10562147076581278824",
                           "name": "赛欧科园科技孵化中心",
                           "phone": "010-83682670",
                           "addr": "北京市丰台区中核路1号院",
                           "classes": "房产小区:产业园区",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508911074,
                           "rankep": 0,
                           "ranktp": 0.488047,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.285860,
                           "pointy": 39.832720,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "281100",
                           "SO": "110106", "POI_PATH": [
		                 {"ccode": 9, "cname": "丰台区"},
		                 {"ccode": 9, "cname": "北京市"},
		                 {"ccode": 2, "cname": "北京市"}],
                           "SH": "919", "BL": " ",
                           "AL": " ", "PL": 97,
                           "CROSS_RANK": "961",
                           "QQ_CLICK": "0",
                           "RELA": "9709.1904296875",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150129154639300",
                                      "x": 12944800.530,
                                      "y": 4841641.550},
                           "master_id": "null",
                           "category_num": "null",
                           "master_slaver_type": "null"},
                          {"uid": "3095548976636287132",
                           "name": "汉庭酒店(北京总部基地科丰桥店)",
                           "phone": "010-63786767",
                           "addr": "北京市丰台区科学城中核路1号",
                           "classes": "酒店宾馆:经济型酒店",
                           "classname": "null",
                           "isbrand": 0, "cs": 219,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.487993,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.285610,
                           "pointy": 39.832290,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "219",
                           "comment_num": "0",
                           "comment_level": "96.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "211500",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "908", "BL": " ",
                           "AL": " ", "PL": 97,
                           "CROSS_RANK": "950",
                           "QQ_CLICK": "0",
                           "RELA": "3478.5024414062",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150130135208200",
                                      "x": 12944866.70,
                                      "y": 4841569.280},
                           "master_id": "10562147076581278824",
                           "category_num": "9",
                           "master_slaver_type": "1"},
                          {"uid": "14684804146781780371",
                           "name": "中核路1号院1号楼",
                           "phone": " ",
                           "addr": "北京市丰台区赛欧科园科技孵化中心1号楼西门",
                           "classes": "房产小区:住宅区:住宅小区",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.879059,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.285490,
                           "pointy": 39.832760,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "281010",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "658", "BL": " ",
                           "AL": " ", "PL": 94,
                           "CROSS_RANK": "380",
                           "QQ_CLICK": "0",
                           "RELA": "2761.6787109375",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150129154640400",
                                      "x": 12944797.180,
                                      "y": 4841653.130},
                           "master_id": "null",
                           "category_num": "null",
                           "master_slaver_type": "null"},
                          {"uid": "8265188780329082088",
                           "name": "赛欧科园科技孵化中心1号楼",
                           "phone": "010-83682670",
                           "addr": "北京市丰台区中核路1号院",
                           "classes": "房产小区:商务楼宇",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.488047,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.285860,
                           "pointy": 39.832720,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "281200",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "799", "BL": " ",
                           "AL": " ", "PL": 97,
                           "CROSS_RANK": "659",
                           "QQ_CLICK": "0",
                           "RELA": "2230.6184082031",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150129154639300",
                                      "x": 12944800.530,
                                      "y": 4841641.550},
                           "master_id": "10562147076581278824",
                           "category_num": "29",
                           "master_slaver_type": "0"},
                          {"uid": "3363576583776884603",
                           "name": "赛欧科园科技孵化中心3号楼",
                           "phone": "010-83682670",
                           "addr": "北京市丰台区中核路1号院",
                           "classes": "房产小区:商务楼宇",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.488047,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.287090,
                           "pointy": 39.832740,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "281200",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "799", "BL": " ",
                           "AL": " ", "PL": 97,
                           "CROSS_RANK": "398",
                           "QQ_CLICK": "0",
                           "RELA": "2187.0454101562",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150130135236400",
                                      "x": 12945038.930,
                                      "y": 4841618.250},
                           "master_id": "10562147076581278824",
                           "category_num": "29",
                           "master_slaver_type": "0"},
                          {"uid": "16271554505675194881",
                           "name": "招商银行(丰台科技园支行)",
                           "phone": "010-83816983",
                           "addr": "北京市丰台区科学城中核路1号03号楼",
                           "classes": "银行金融:银行",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.487870,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.287020,
                           "pointy": 39.832870,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "251000",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "650", "BL": " ",
                           "AL": " ", "PL": 97,
                           "CROSS_RANK": "884",
                           "QQ_CLICK": "0",
                           "RELA": "-4337.9121093750",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150130135230200",
                                      "x": 12945027.490,
                                      "y": 4841614.750},
                           "master_id": "10562147076581278824",
                           "category_num": "9",
                           "master_slaver_type": "1"},
                          {"uid": "17842393323162104333",
                           "name": "赛欧科园科技孵化中心2号楼",
                           "phone": "010-83682670",
                           "addr": "北京市丰台区中核路1号院2",
                           "classes": "房产小区:商务楼宇",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.487993,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.286200,
                           "pointy": 39.832800,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "281200",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "631", "BL": " ",
                           "AL": " ", "PL": 97,
                           "CROSS_RANK": "364",
                           "QQ_CLICK": "0",
                           "RELA": "-5089.0610351562",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150130135217700",
                                      "x": 12944947.680,
                                      "y": 4841592.380},
                           "master_id": "10562147076581278824",
                           "category_num": "29",
                           "master_slaver_type": "0"},
                          {"uid": "8628828123851686459",
                           "name": "北京京诚华宇建筑设计院",
                           "phone": " ",
                           "addr": "北京市丰台区中核路1号03号楼8层",
                           "classes": "机构团体:科研机构",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.487870,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.287830,
                           "pointy": 39.831350,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "121900",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "772", "BL": " ",
                           "AL": " ", "PL": 93,
                           "CROSS_RANK": "422",
                           "QQ_CLICK": "0",
                           "RELA": "-7124.0117187500",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150130134458000",
                                      "x": 12945128.770,
                                      "y": 4841407.560},
                           "master_id": "7611575050059138802",
                           "category_num": "8",
                           "master_slaver_type": "1"},
                          {"uid": "12441633920376850128",
                           "name": "赛欧5F咖啡",
                           "phone": "010-83628582",
                           "addr": "北京市丰台区中核路一号赛欧科园科技孵化中心一号楼一层",
                           "classes": "娱乐休闲:咖啡厅",
                           "classname": "null",
                           "isbrand": 0, "cs": 32,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.487709,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.286010,
                           "pointy": 39.832710,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "32",
                           "comment_num": "0",
                           "comment_level": "70.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "161300",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "655", "BL": " ",
                           "AL": " ", "PL": 94,
                           "CROSS_RANK": "432",
                           "QQ_CLICK": "0",
                           "RELA": "-11150.2275390625",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011013150130135215000",
                                      "x": 12944924.570,
                                      "y": 4841585.590},
                           "master_id": "10562147076581278824",
                           "category_num": "9",
                           "master_slaver_type": "1"},
                          {"uid": "2320708555565913121",
                           "name": "北京当瑟国际舞蹈艺术中心",
                           "phone": " ",
                           "addr": "北京市丰台区中核路1号赛欧科园孵化中心3号楼15层",
                           "classes": "运动健身:舞蹈",
                           "classname": "null",
                           "isbrand": 0, "cs": 0,
                           "xgc_st": 0, "xgc_to": 0,
                           "xgc_ms": 0, "tag": [],
                           "timestamp": 1508612341,
                           "rankep": 0,
                           "ranktp": 0.487731,
                           "rankqp": 0, "zip": " ",
                           "pinfo": "",
                           "pointx": 116.284190,
                           "pointy": 39.851140,
                           "geotype": 0, "poitype": 0,
                           "src": 0, "detail": 1,
                           "dis": 0.00,
                           "average_price": "0",
                           "comment_num": "0",
                           "comment_level": "0.000000",
                           "special_rec": " ",
                           "pic_id": " ", "CO": "182900",
                           "SO": "110106", "POI_PATH": [
	                          {"ccode": 9,
	                           "cname": "丰台区"},
	                          {"ccode": 9,
	                           "cname": "北京市"},
	                          {"ccode": 2,
	                           "cname": "北京市"}],
                           "SH": "500", "BL": " ",
                           "AL": " ", "PL": 93,
                           "CROSS_RANK": "343",
                           "QQ_CLICK": "0",
                           "RELA": "-16754.2402343750",
                           "base_url": "", "isxp": 100,
                           "richInfo": 0,
                           "floor_name": " ",
                           "is_inside": 0,
                           "inside_class": " ",
                           "xpinfo": {"src": 1,
                                      "svid": "10011039131004145852000",
                                      "x": 12944694.410,
                                      "y": 4844353.40},
                           "master_id": "null",
                           "category_num": "null",
                           "master_slaver_type": "null"}],
                 "subpois": {},
                 "backlink": {"type": 2, "acode": 0,
                              "ccode": 1, "cname": "中国",
                              "query": ""},
                 "geoInfo": {}}}
